### ISSUE TITLE
Windows Incompatibilities

### ISSUE THREAD

**Issue by londospark** [cmgriffing/servante#7]
The package.json file has commands that won't work in Windows (either cmd or powershell), having had a brief look at this it looks like `&&` is used which Windows doesn't like and in Windows `cp` doesn't have a `-a` parameter.

I think `;` will work in Windows rather than `&&` but don't have a `-a` alternative yet. Would it be worth adding something like https://www.npmjs.com/package/shelljs or https://www.npmjs.com/package/cross-env to help with these differences?

**Comment by cmgriffing** [comment]
Thanks. I ended up implementing shx.
